#!/bin/bash

PATH="$(yarn global bin):$PATH"

alias ll='ls -alF'

alias push='git push origin --follow-tags'
alias ws="yarn workspace"

function tag()
{
  if [[ $(git status -s) ]];
    then
      echo "Git repo has uncommitted changes."
      git status -s;
    else
      git tag -a "v${1}" -m "v${1}";
  fi
}

function dev ()
{
  hugo server -D
}

function build ()
{
  hugo --minify
}
